version: 2

workflows:
  version: 2
  build-master:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master

jobs:
  build-and-deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
          export DOCKER_TAG=$(echo $DOCKER_REPO_URL:$SHORT_GIT_HASH)
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker
          docker build -t $DOCKER_IMAGE_NAME fee-relayer
          docker tag $DOCKER_IMAGE_NAME $DOCKER_TAG
          docker push $DOCKER_TAG
